version: "3.6"
services:

#Portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASEDIR}/docker/portainer/data:/data
      - ${BASEDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}

# Organizer - Unified HTPC/Home Server Web Interface
  organizr:
    container_name: organizr
    hostname: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - ${BASEDIR}/docker/organizr:/config
      - ${BASEDIR}/docker/shared:/shared
    ports:
      - "80:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# WebUI for MariaDB
  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mariadb:db
    ports:
      - 81:80
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

######### DOCKER RELATED ##########

# Watchtower - Automatic Update of Containers/Apps
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

######### SMART HOME APPS ##########

# Home Assistant - Smart Home Hub
  homeassistant:
    container_name: homeassistant
    hostname: hass
    restart: always
    image: homeassistant/home-assistant
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    #  - /dev/ttyUSB1:/dev/ttyUSB1
    #  - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ${BASEDIR}/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${BASEDIR}/docker/shared:/shared
    ports:
      - "8123:8123"
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}


# qBittorrent
  qbittorrent:
    image: "linuxserver/qbittorrent"
    hostname: qbittorrent
    container_name: "qbittorrent"
    volumes:
      - ${BASEDIR}/docker/qbittorrent:/config
      - ${BASEDIR}/Downloads/completed:/downloads
      - ${BASEDIR}/docker/shared:/shared
    ports:
      - "8124:8124"
      - "6881:6881"
      - "6881:6881/udp"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      - WEBUI_PORT=8124

# Radarr
  radarr:
    image: "linuxserver/radarr"
    hostname: radarr
    container_name: "radarr"
    volumes:
      - ${BASEDIR}/docker/radarr:/config
      - ${BASEDIR}/Downloads/completed:/downloads
      - ${BASEDIR}/media/movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - ${BASEDIR}/docker/shared:/shared
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Sonarr
  sonarr:
    image: "linuxserver/sonarr"
    hostname: sonarr
    container_name: "sonarr"
    volumes:
      - ${BASEDIR}/docker/sonarr:/config
      - ${BASEDIR}/Downloads/completed:/downloads
      - ${BASEDIR}/media/tvshows:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - ${BASEDIR}/docker/shared:/shared
    ports:
        - "8989:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Plex Media Server
  plexms:
    container_name: plexms
    hostname: plexms
    restart: always
    image: plexinc/pms-docker
    volumes:
      - ${BASEDIR}/docker/plexms:/config
      - ${BASEDIR}/Downloads/plex_tmp:/transcode
      - ${BASEDIR}/media:/media
      - ${BASEDIR}/docker/shared:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP="http://proxmox:32400/"

# Tautulli (aka PlexPy) – Monitoring Plex Usage
  tautulli:
    container_name: tautulli
    hostname: tautulli
    restart: always
    image: linuxserver/tautulli
    volumes:
      - ${BASEDIR}/docker/tautulli/config:/config
      - ${BASEDIR}/docker/tautulli/logs:/logs:ro
      - ${BASEDIR}/docker/shared:/shared
    ports:
      - "8181:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}  

# Ombi – Accept Requests for your Media Server
  ombi:
    container_name: ombi
    hostname: ombi
    restart: always
    image: linuxserver/ombi
    volumes:
      - ${BASEDIR}/docker/ombi:/config
      - ${BASEDIR}/docker/shared:/shared
    ports:
      - "3579:3579"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Jackett – Torrent Proxy
  jackett:
    image: "linuxserver/jackett"
    hostname: jackett
    container_name: "jackett"
    volumes:
      - ${BASEDIR}/docker/jackett:/config
      - ${BASEDIR}/Downloads/completed:/downloads
      - "/etc/localtime:/etc/localtime:ro"
      - ${BASEDIR}/docker/shared:/shared
    ports:
      - "9117:9117"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# MariaDB – Database Server for your Apps
  mariadb:
    image: "linuxserver/mariadb"
    container_name: "mariadb"
    hostname: mariadb
    volumes:
        - ${BASEDIR}/docker/mariadb:/config
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# NextCloud – Your Own Cloud Storage
  nextcloud:
    container_name: nextcloud
    hostname: nextcloud
    restart: always
    image: linuxserver/nextcloud
    volumes:
      - ${BASEDIR}/docker/nextcloud:/config
      - ${BASEDIR}/shared_data:/data
      - ${BASEDIR}/docker/shared:/shared
    ports:
      - "443:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
